use_frameworks!
platform :ios, '10.0'

target 'StaticExample_Example' do
  pod 'StaticExample', :path => '../'

  target 'StaticExample_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3'
    pod 'Nimble', '~> 7.1'
  end
end
