use_frameworks!
platform :ios, '10.0'

target 'DynamicExample_Example' do
  pod 'DynamicExample', :path => '../'

  target 'DynamicExample_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3'
    pod 'Nimble', '~> 7.1'
  end
end
